### ISSUE TITLE
Loot Tables not working

### ISSUE THREAD

**Issue by ereese99** [Hir0shiyt/Hir0shiyt-Trident-Crafting-And-Structures-Forge#1]
Unable to fill loot chest in ResourceKey[minecraft:dimension / minecraft:overworld] at class_2338{x=202, y=40, z=43} as the loot table 'trident_crafting__structures_two:chests' couldn't be resolved! Please search the loot table in `latest.log` to see if there are errors in loading.

**Comment by Hir0shiyt** [comment]
Wrong github repository
